### PR TITLE
added first component from session -login

### PR DESCRIPTION
**Pull request by MGeovany**

### CODE REVIEW

**Comment by MGeovany** [comment]
all good, assets are not sync

**Comment by MGeovany** [comment]
all good, reviewed, will need to keep working on this branch for the signup

**Comment by MGeovany** [comment]
will need to keep working on this branch for the signup section

**Comment by MGeovany** [comment]
will need to keep working on this branch for the signup section

**Review by mgeovanydev — APPROVED** [review]
will confirm pull request 🛸

**Pull request merged**
